server {
    listen 80;
    server_name sanctificare.app www.sanctificare.app;
    
    # Redirecionar todo tráfego HTTP para HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name sanctificare.app www.sanctificare.app;

    # Certificados SSL (Gerenciados pelo Let's Encrypt / Certbot)
    ssl_certificate /etc/letsencrypt/live/sanctificare.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sanctificare.app/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
