import { useState } from "react";
import { Check, Crown, Headphones, Heart, Lock, Pause, Play, Timer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { UpgradeDialog } from "@/components/UpgradeDialog";
import type { JourneyDay } from "@/data/saint-michael-lent";

export function JourneyHeader({ title, subtitle, image }: { title: string; subtitle: string; image: string }) {
  return <header className="relative overflow-hidden border border-[oklch(0.7_0.1_75/0.28)] bg-[oklch(0.22_0.07_260)] text-white">
    <img src={image} alt="São Miguel Arcanjo" className="absolute inset-0 h-full w-full object-cover opacity-25" />
    <div className="relative p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Jornada espiritual</p><h1 className="font-display mt-2 text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-2 max-w-xl font-serif text-sm text-slate-200">{subtitle}</p></div>
  </header>;
}

export function JourneyProgress({ completed, total, streak }: { completed: number; total: number; streak: number }) {
  const percent = Math.round((completed / total) * 100);
  return <section className="border border-border bg-background p-4"><div className="flex justify-between text-sm"><span className="font-semibold">{completed} de {total} dias concluídos</span><span className="text-muted-foreground">Sequência: {streak} dias</span></div><div className="mt-3 h-2 bg-muted"><div className="h-full bg-[oklch(0.65_0.12_70)]" style={{ width: `${percent}%` }} /></div></section>;
}

export function JourneyCalendar({ completed, selectedDay, onSelect }: { completed: number[]; selectedDay: number; onSelect: (day: number) => void }) {
  return <section aria-label="Calendário da jornada" className="border border-border bg-background p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Calendário da jornada</p><div className="grid grid-cols-8 gap-1.5">{Array.from({ length: 40 }, (_, index) => index + 1).map((day) => <button key={day} onClick={() => onSelect(day)} className={`aspect-square text-xs font-semibold ${day === selectedDay ? "bg-[oklch(0.22_0.07_260)] text-white" : completed.includes(day) ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200" : "bg-muted text-muted-foreground"}`}>{completed.includes(day) ? <Check className="mx-auto h-3.5 w-3.5" /> : day}</button>)}</div></section>;
}

export function TraditionalPrayerSection({ children }: { children: React.ReactNode }) {
  return <section className="border border-[oklch(0.7_0.1_75/0.32)] bg-background"><div className="border-b border-[oklch(0.7_0.1_75/0.22)] bg-[oklch(0.95_0.03_85)] px-5 py-4 dark:bg-[oklch(0.22_0.04_70)]"><p className="text-xs font-bold uppercase tracking-wider text-[oklch(0.55_0.12_65)]">Devoção Tradicional - acesso gratuito</p><p className="mt-1 text-sm text-muted-foreground">Orações preservadas integralmente para todos.</p></div>{children}</section>;
}

export function PrayerReader({ prayers, fontSize, onNext }: { prayers: readonly { title: string; content: string }[]; fontSize: string; onNext: () => void }) {
  return <div className="p-5"><Accordion type="single" collapsible defaultValue="prayer-0">{prayers.map((prayer, index) => <AccordionItem key={prayer.title} value={`prayer-${index}`}><AccordionTrigger>{index + 1}. {prayer.title}</AccordionTrigger><AccordionContent className={`${fontSize} whitespace-pre-line font-serif leading-relaxed text-foreground`}>{prayer.content}</AccordionContent></AccordionItem>)}</Accordion><Button onClick={onNext} className="mt-5 w-full">Próxima oração</Button></div>;
}

export function PrayerAudioPlayer() { const [playing, setPlaying] = useState(false); return <div className="mx-5 mb-5 flex items-center gap-3 border border-border p-3 text-sm text-muted-foreground"><Button variant="outline" size="icon" onClick={() => setPlaying(!playing)} aria-label="Reproduzir áudio da oração">{playing ? <Pause size={16} /> : <Play size={16} />}</Button><Headphones size={16} /><span>Áudio da oração será disponibilizado gratuitamente em breve.</span></div>; }

export function DailyThemeCard({ day }: { day: JourneyDay }) { return <section className="border border-border bg-background p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[oklch(0.55_0.12_65)]">Tema do dia</p><h2 className="font-display mt-1 text-2xl font-bold">{day.theme}</h2></section>; }
export function ScriptureCard({ day }: { day: JourneyDay }) { return <section className="border-l-4 border-[oklch(0.65_0.12_70)] bg-muted/50 p-5"><p className="font-semibold">Palavra de Deus - {day.scripture.reference}</p><p className="mt-2 font-serif leading-relaxed">{day.scripture.text}</p></section>; }
export function MeditationCard({ day }: { day: JourneyDay }) { return <section><h3 className="font-display text-xl font-bold">Meditação</h3><p className="mt-2 font-serif leading-relaxed text-muted-foreground">{day.meditation}</p></section>; }
export function VirtueCard({ day }: { day: JourneyDay }) { return <section className="border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Virtude do dia</p><p className="mt-1 font-display text-xl font-bold">{day.virtue}</p></section>; }
export function DailyPurposeCard({ day }: { day: JourneyDay }) { return <section className="border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Propósito concreto</p><p className="mt-1 text-sm leading-relaxed">{day.purpose}</p></section>; }
export function PenanceCard({ text }: { text: string }) { return <section className="border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Penitência sugerida</p><p className="mt-1 text-sm leading-relaxed">{text}</p></section>; }
export function ExaminationOfConscience({ questions }: { questions: string[] }) { return <section><h3 className="font-display text-xl font-bold">Exame de consciência</h3><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{questions.map(question => <li key={question}>- {question}</li>)}</ul></section>; }

export function SpiritualJournal({ value, onSave, onDelete }: { value: string; onSave: (value: string) => void; onDelete: () => void }) { const [text, setText] = useState(value); return <section className="border border-border p-5"><div className="flex items-center justify-between"><h3 className="font-display text-xl font-bold">Diário espiritual</h3><span className="text-xs text-muted-foreground">Privado</span></div><Textarea value={text} onChange={event => setText(event.target.value)} placeholder="Guarde aqui o que o Senhor suscitou em seu coração..." className="mt-3 min-h-32" /><div className="mt-3 flex gap-2"><Button onClick={() => onSave(text)}>Salvar anotação</Button><Button variant="ghost" onClick={() => { setText(""); onDelete(); }}>Excluir</Button></div></section>; }

export function ReminderSettings({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="flex items-center justify-between border border-border p-4 text-sm"><span><span className="block font-semibold">Lembrete de oração</span><span className="text-xs text-muted-foreground">Escolha um horário diário.</span></span><input type="time" value={value} onChange={event => onChange(event.target.value)} className="border border-border bg-background px-2 py-1" /></label>; }

export function SubscriptionOffer() { const [open, setOpen] = useState(false); return <><section className="border border-[oklch(0.7_0.1_75/0.35)] bg-[oklch(0.97_0.02_85)] p-5 dark:bg-[oklch(0.2_0.04_70)]"><Crown className="h-5 w-5 text-[oklch(0.65_0.12_70)]" /><h3 className="font-display mt-2 text-xl font-bold">Aprofunde esta experiência com o Sanctificare Premium</h3><p className="mt-2 text-sm text-muted-foreground">A devoção tradicional permanece gratuita. O Premium oferece meditações, áudios e exercícios espirituais para sua caminhada.</p><Button variant="outline" className="mt-4" onClick={() => setOpen(true)}><Lock className="mr-2 h-4 w-4" />Conhecer o aprofundamento</Button></section><UpgradeDialog open={open} onOpenChange={setOpen} description="Continue com meditações, áudios e exercícios espirituais da Quaresma de São Miguel." /></>; }

export function PremiumDepthSection({ day, journal, onJournalSave, onJournalDelete }: { day: JourneyDay; journal: string; onJournalSave: (value: string) => void; onJournalDelete: () => void }) { const [favorite, setFavorite] = useState(false); return <section className="space-y-5 border border-[oklch(0.7_0.1_75/0.35)] bg-background p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[oklch(0.55_0.12_65)]">Aprofundamento Espiritual - Sanctificare Premium</p><h2 className="font-display mt-1 text-2xl font-bold">{day.theme}</h2></div><Button variant="ghost" size="icon" onClick={() => setFavorite(!favorite)} aria-label="Favoritar conteúdo"><Heart className={favorite ? "fill-red-500 text-red-500" : ""} size={18} /></Button></div><ScriptureCard day={day} /><MeditationCard day={day} /><div className="flex items-center gap-3 border border-border p-4 text-sm"><Headphones size={17} /><span>Meditação narrada e áudio contemplativo serão associados a este dia.</span></div><div className="grid gap-3 sm:grid-cols-2"><VirtueCard day={day} /><DailyPurposeCard day={day} /></div><PenanceCard text={day.suggestedPenance} /><ExaminationOfConscience questions={day.examination} /><SpiritualJournal value={journal} onSave={onJournalSave} onDelete={onJournalDelete} /><section><h3 className="font-display text-xl font-bold">Oração complementar</h3><p className="mt-2 whitespace-pre-line font-serif leading-relaxed text-muted-foreground">{day.complementaryPrayer}</p><p className="mt-4 text-sm italic text-muted-foreground">{day.saintQuote}</p></section><div className="flex items-center gap-3 border border-border p-4 text-sm"><Timer size={17} /><span>Cronômetro de silêncio contemplativo</span><Button variant="outline" size="sm" className="ml-auto">Iniciar</Button></div></section>; }

export function CompletionScreen({ completed, total, onFinish, onDepth }: { completed: number; total: number; onFinish: () => void; onDepth: () => void }) { return <section className="border border-emerald-300 bg-emerald-50 p-6 text-center dark:border-emerald-800 dark:bg-emerald-950/30"><Check className="mx-auto h-8 w-8 text-emerald-700" /><h2 className="font-display mt-3 text-2xl font-bold">Dia concluído</h2><p className="mt-2 text-sm text-muted-foreground">A devoção tradicional foi realizada integralmente.</p><p className="mt-3 text-sm font-semibold">{completed} de {total} dias na jornada</p><div className="mt-5 flex flex-col justify-center gap-2 sm:flex-row"><Button onClick={onFinish}>Finalizar</Button><Button variant="outline" onClick={onDepth}>Aprofundar a oração de hoje</Button></div></section>; }